package com.inventory.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;

@Document(collection = "purchase_orders")
public class PurchaseOrder {
    @Id
    private String id;
    private String productId;
    private String productName;
    private int quantityToOrder;
    private String vendorEmail;
    
    // Status now tracks vendor confirmation
    private String status; 
    
    private LocalDateTime createdAt;
    
    // These two are required for Vendor Tracking logic
    private String confirmationToken;
    private LocalDateTime confirmedAt; 

    // Getters and Setters (auto-generated by Lombok if @Data is used, or explicit if not)
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getProductId() { return productId; }
    public void setProductId(String productId) { this.productId = productId; }
    public String getProductName() { return productName; }
    public void setProductName(String productName) { this.productName = productName; }
    public int getQuantityToOrder() { return quantityToOrder; }
    public void setQuantityToOrder(int quantityToOrder) { this.quantityToOrder = quantityToOrder; }
    public String getVendorEmail() { return vendorEmail; }
    public void setVendorEmail(String vendorEmail) { this.vendorEmail = vendorEmail; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    // Lombok is assumed for these, but you've added them manually, which is fine
    public String getConfirmationToken() { return confirmationToken; }
    public void setConfirmationToken(String confirmationToken) { this.confirmationToken = confirmationToken; }
    public LocalDateTime getConfirmedAt() { return confirmedAt; }
    public void setConfirmedAt(LocalDateTime confirmedAt) { this.confirmedAt = confirmedAt; }
}