# MongoDB Connection (MongoDB Atlas)
spring.data.mongodb.uri=mongodb+srv://MbarathProject:Mbarath123@barathm.bj8jc.mongodb.net/inventory_db?retryWrites=true&w=majority&appName=barath
# Local fallback: spring.data.mongodb.uri=mongodb://localhost:27017/inventory_db

# JWT Secret Key (Change this to a long, random string!)
# This is a strong, 64-character key
app.jwt.secret=q8TfP!n2R$E@y6KjV#mZp*u9A(G+KbPeSgVkYp3s5v8y/B?D)F-JaNdRfWmXqZr4 
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mbarathforclg@gmail.com
spring.mail.password=aaif iqqh lkap xble
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true